# coding: utf-8
from sqlalchemy import Column, DateTime, Float, String
from sqlalchemy.dialects.mysql import INTEGER, LONGTEXT, VARCHAR
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class TABLEHRDCONTACTSV01(Base):
    __tablename__ = 'TABLE_HRD_CONTACTS_V01'

    COL_PRIMARY_KEY = Column(INTEGER(11), primary_key=True)
    COL_ADDRESS = Column(VARCHAR(255))
    COL_AGE = Column(INTEGER(11))
    COL_A_INDEX = Column(Float(asdecimal=True))
    COL_ANT_AZ = Column(Float(asdecimal=True))
    COL_ANT_EL = Column(Float(asdecimal=True))
    COL_ANT_PATH = Column(String(2))
    COL_ARRL_SECT = Column(String(10))
    COL_BAND = Column(String(10), index=True)
    COL_BAND_RX = Column(String(10))
    COL_BIOGRAPHY = Column(LONGTEXT)
    COL_CALL = Column(String(32), index=True)
    COL_CHECK = Column(String(8))
    COL_CLASS = Column(String(8))
    COL_CNTY = Column(String(32))
    COL_COMMENT = Column(LONGTEXT)
    COL_CONT = Column(String(6), index=True)
    COL_CONTACTED_OP = Column(String(32))
    COL_CONTEST_ID = Column(String(32))
    COL_COUNTRY = Column(String(64))
    COL_CQZ = Column(INTEGER(11))
    COL_DISTANCE = Column(Float(asdecimal=True))
    COL_DXCC = Column(String(6), index=True)
    COL_EMAIL = Column(String(32))
    COL_EQ_CALL = Column(String(32))
    COL_EQSL_QSLRDATE = Column(DateTime)
    COL_EQSL_QSLSDATE = Column(DateTime)
    COL_EQSL_QSL_RCVD = Column(String(2))
    COL_EQSL_QSL_SENT = Column(String(2))
    COL_EQSL_STATUS = Column(String(255))
    COL_FORCE_INIT = Column(INTEGER(11))
    COL_FREQ = Column(INTEGER(11))
    COL_FREQ_RX = Column(INTEGER(11))
    COL_GRIDSQUARE = Column(String(12))
    COL_HEADING = Column(Float(asdecimal=True))
    COL_IOTA = Column(String(10), index=True)
    COL_ITUZ = Column(INTEGER(11))
    COL_K_INDEX = Column(Float(asdecimal=True))
    COL_LAT = Column(Float(asdecimal=True))
    COL_LON = Column(Float(asdecimal=True))
    COL_LOTW_QSLRDATE = Column(DateTime)
    COL_LOTW_QSLSDATE = Column(DateTime)
    COL_LOTW_QSL_RCVD = Column(String(2))
    COL_LOTW_QSL_SENT = Column(String(2))
    COL_LOTW_STATUS = Column(String(255))
    COL_MAX_BURSTS = Column(INTEGER(11))
    COL_MODE = Column(String(10), index=True)
    COL_MS_SHOWER = Column(String(32))
    COL_MY_CITY = Column(VARCHAR(32))
    COL_MY_CNTY = Column(String(32))
    COL_MY_COUNTRY = Column(String(64))
    COL_MY_CQ_ZONE = Column(INTEGER(11))
    COL_MY_GRIDSQUARE = Column(String(12))
    COL_MY_IOTA = Column(String(10))
    COL_MY_ITU_ZONE = Column(INTEGER(11))
    COL_MY_LAT = Column(Float(asdecimal=True))
    COL_MY_LON = Column(Float(asdecimal=True))
    COL_MY_NAME = Column(VARCHAR(64))
    COL_MY_POSTAL_CODE = Column(String(24))
    COL_MY_RIG = Column(VARCHAR(255))
    COL_MY_SIG = Column(String(32))
    COL_MY_SIG_INFO = Column(String(64))
    COL_MY_STATE = Column(String(32))
    COL_MY_STREET = Column(VARCHAR(64))
    COL_NAME = Column(VARCHAR(128))
    COL_NOTES = Column(LONGTEXT)
    COL_NR_BURSTS = Column(INTEGER(11))
    COL_NR_PINGS = Column(INTEGER(11))
    COL_OPERATOR = Column(String(32))
    COL_OWNER_CALLSIGN = Column(String(32))
    COL_PFX = Column(String(32), index=True)
    COL_PRECEDENCE = Column(String(32))
    COL_PROP_MODE = Column(String(8))
    COL_PUBLIC_KEY = Column(String(255))
    COL_QSLMSG = Column(VARCHAR(255))
    COL_QSLRDATE = Column(DateTime)
    COL_QSLSDATE = Column(DateTime)
    COL_QSL_RCVD = Column(String(2))
    COL_QSL_RCVD_VIA = Column(String(2))
    COL_QSL_SENT = Column(String(2))
    COL_QSL_SENT_VIA = Column(String(2))
    COL_QSL_VIA = Column(String(64))
    COL_QSO_COMPLETE = Column(String(6))
    COL_QSO_RANDOM = Column(INTEGER(11))
    COL_QTH = Column(VARCHAR(64))
    COL_RIG = Column(String(255))
    COL_RST_RCVD = Column(String(32))
    COL_RST_SENT = Column(String(32))
    COL_RX_PWR = Column(Float(asdecimal=True))
    COL_SAT_MODE = Column(String(32))
    COL_SAT_NAME = Column(String(32))
    COL_SFI = Column(Float(asdecimal=True))
    COL_SIG = Column(String(32))
    COL_SIG_INFO = Column(String(64))
    COL_SRX = Column(INTEGER(11))
    COL_SRX_STRING = Column(String(32))
    COL_STATE = Column(String(32))
    COL_STATION_CALLSIGN = Column(String(32))
    COL_STX = Column(INTEGER(11))
    COL_STX_STRING = Column(String(32))
    COL_SWL = Column(INTEGER(11))
    COL_TEN_TEN = Column(INTEGER(11))
    COL_TIME_OFF = Column(DateTime)
    COL_TIME_ON = Column(DateTime, index=True)
    COL_TX_PWR = Column(Float(asdecimal=True))
    COL_WEB = Column(String(128))
    COL_USER_DEFINED_0 = Column(String(64))
    COL_USER_DEFINED_1 = Column(String(64))
    COL_USER_DEFINED_2 = Column(String(64))
    COL_USER_DEFINED_3 = Column(String(64))
    COL_USER_DEFINED_4 = Column(String(64))
    COL_USER_DEFINED_5 = Column(String(64))
    COL_USER_DEFINED_6 = Column(String(64))
    COL_USER_DEFINED_7 = Column(String(64))
    COL_USER_DEFINED_8 = Column(String(64))
    COL_USER_DEFINED_9 = Column(DateTime)
    COL_CREDIT_GRANTED = Column(String(64))
    COL_CREDIT_SUBMITTED = Column(String(64))
    COL_ISMULTIPLIER = Column(String(64))
    COL_ROVERLOCATION = Column(String(64))
    COL_HRDCOUNTRYNO = Column(String(64))
    COL_SUBMODE = Column(String(10))