"""initial

Revision ID: df1c35a33803
Revises: 
Create Date: 2022-10-16 12:10:37.955204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1c35a33803'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WSJTX_Decode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('New', sa.Boolean(), nullable=True),
    sa.Column('Time', sa.Integer(), nullable=True),
    sa.Column('snr', sa.Integer(), nullable=True),
    sa.Column('DeltaTime', sa.Float(), nullable=True),
    sa.Column('DeltaFrequency', sa.Integer(), nullable=True),
    sa.Column('Mode', sa.String(), nullable=True),
    sa.Column('Message', sa.String(), nullable=True),
    sa.Column('LowConfidence', sa.Boolean(), nullable=True),
    sa.Column('OffAir', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WSJTX_Logged',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('DateOff', sa.Integer(), nullable=True),
    sa.Column('TimeOff', sa.Integer(), nullable=True),
    sa.Column('TimeOffSpec', sa.Integer(), nullable=True),
    sa.Column('TimeOffOffset', sa.Integer(), nullable=True),
    sa.Column('DXcall', sa.String(), nullable=True),
    sa.Column('DXgrid', sa.String(), nullable=True),
    sa.Column('DialFrequency', sa.Integer(), nullable=True),
    sa.Column('Mode', sa.String(), nullable=True),
    sa.Column('ReportSent', sa.String(), nullable=True),
    sa.Column('ReportReceived', sa.String(), nullable=True),
    sa.Column('TxPower', sa.String(), nullable=True),
    sa.Column('Comments', sa.String(), nullable=True),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('DateOn', sa.Integer(), nullable=True),
    sa.Column('TimeOn', sa.Integer(), nullable=True),
    sa.Column('TimeOnSpec', sa.Integer(), nullable=True),
    sa.Column('TimeOnOffset', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WSJTX_Status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Frequency', sa.Integer(), nullable=True),
    sa.Column('Mode', sa.String(), nullable=True),
    sa.Column('DXCall', sa.String(), nullable=True),
    sa.Column('Report', sa.String(), nullable=True),
    sa.Column('TxMode', sa.String(), nullable=True),
    sa.Column('TxEnabled', sa.Boolean(), nullable=True),
    sa.Column('Transmitting', sa.Boolean(), nullable=True),
    sa.Column('Decoding', sa.Boolean(), nullable=True),
    sa.Column('RxDF', sa.Integer(), nullable=True),
    sa.Column('TxDF', sa.Integer(), nullable=True),
    sa.Column('DECall', sa.String(), nullable=True),
    sa.Column('DEgrid', sa.String(), nullable=True),
    sa.Column('DXgrid', sa.String(), nullable=True),
    sa.Column('TxWatchdog', sa.Boolean(), nullable=True),
    sa.Column('Submode', sa.String(), nullable=True),
    sa.Column('Fastmode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WSJTX_Status')
    op.drop_table('WSJTX_Logged')
    op.drop_table('WSJTX_Decode')
    # ### end Alembic commands ###
